#include "doctest.h"
#include "commands.hpp"
#include "test_helpers.hpp"

#include <stdexcept>

/** This file was generated by Claude  **/

using namespace std;

TEST_CASE("Test commands::ends_with") {
	CHECK(ends_with("graph.1path", ".1path"));
	CHECK(ends_with("graph.1gbwt", ".1gbwt"));
	CHECK(ends_with(".1path", ".1path"));
	CHECK_FALSE(ends_with("graph.1path", ".1gbwt"));
	CHECK_FALSE(ends_with("graph.1path.gz", ".1path"));
	CHECK_FALSE(ends_with("path", ".1path"));
	CHECK(ends_with("anything", ""));
}

TEST_CASE("Test commands::check_open_file") {
	CHECK_NOTHROW(check_open_file(data_path("small.1path"), "path"));
	CHECK_NOTHROW(check_open_file(data_path("small.1gbwt"), "gbwt"));
	CHECK_NOTHROW(check_open_file(data_path("small.1khash"), "khash"));
	CHECK_THROWS_AS(check_open_file(data_path("non-existent.1path"), "path"), runtime_error);
}

TEST_CASE("Test commands::create_histogram") {
	string path = data_path("small.1path");
	string gbwt = data_path("small.1gbwt");
	string khash = data_path("small.1khash");

	SUBCASE("path file") {
		string out = output_path("cli_hist_path");
		Args args({"syncmer-toolkit", "histogram", path, khash, out});
		CHECK(create_histogram(args.argc(), args.data()) == 0);
		CHECK(file_exists(out + "_syncmers.tsv"));
		CHECK(file_exists(out + "_histogram.tsv"));
	}

	SUBCASE("gbwt file") {
		string out = output_path("cli_hist_gbwt");
		Args args({"syncmer-toolkit", "histogram", gbwt, khash, out});
		CHECK(create_histogram(args.argc(), args.data()) == 0);
		CHECK(file_exists(out + "_syncmers.tsv"));
		CHECK(file_exists(out + "_histogram.tsv"));
	}

	SUBCASE("too few arguments") {
		Args args({"syncmer-toolkit", "histogram", path, khash});
		CHECK(create_histogram(args.argc(), args.data()) == 1);
	}

	SUBCASE("too many arguments") {
		Args args({"syncmer-toolkit", "histogram", path, khash, output_path("cli_x"), "extra"});
		CHECK(create_histogram(args.argc(), args.data()) == 1);
	}

	SUBCASE("unsupported file extension") {
		Args args({"syncmer-toolkit", "histogram", data_path("small_subset.tsv"), khash, output_path("cli_ext")});
		CHECK(create_histogram(args.argc(), args.data()) == 1);
	}

	SUBCASE("input file cannot be opened") {
		string out = output_path("cli_hist_missing");
		Args args({"syncmer-toolkit", "histogram", data_path("non-existent.1path"), khash, out});
		CHECK(create_histogram(args.argc(), args.data()) == 1);
		CHECK_FALSE(file_exists(out + "_syncmers.tsv"));
	}

	SUBCASE("khash file cannot be opened") {
		Args args({"syncmer-toolkit", "histogram", path, data_path("non-existent.1khash"), output_path("cli_nokhash")});
		CHECK(create_histogram(args.argc(), args.data()) == 1);
	}
}

TEST_CASE("Test commands::compute_distances") {
	string path = data_path("small.1path");
	string khash = data_path("small.1khash");
	string subset = data_path("small_subset.tsv");

	SUBCASE("valid input") {
		string out = output_path("cli_distances.tsv");
		Args args({"syncmer-toolkit", "distances", path, khash, subset, out});
		CHECK(compute_distances(args.argc(), args.data()) == 0);
		CHECK(file_exists(out));
	}

	SUBCASE("too few arguments") {
		Args args({"syncmer-toolkit", "distances", path, khash, subset});
		CHECK(compute_distances(args.argc(), args.data()) == 1);
	}

	SUBCASE("too many arguments") {
		Args args({"syncmer-toolkit", "distances", path, khash, subset, output_path("cli_y"), "extra"});
		CHECK(compute_distances(args.argc(), args.data()) == 1);
	}

	SUBCASE("path file cannot be opened") {
		Args args({"syncmer-toolkit", "distances", data_path("non-existent.1path"), khash, subset, output_path("cli_z")});
		CHECK(compute_distances(args.argc(), args.data()) == 1);
	}
}
