#include "doctest.h"
#include "syncmerstats.hpp"
#include <stdexcept>

using namespace std;

TEST_CASE("Test syncmerstats::count: counting.") {
	vector<int32_t> counts = {0,0,0};
	increase_syncmer_count(counts, 1);
	CHECK(counts[1] == 1);
	counts[0] = -1;
	increase_syncmer_count(counts, 0);
	CHECK(counts[0] == -1);
}

TEST_CASE("Test syncmerstats::visit: counting.") {
	vector<int32_t> counts = {0,2,3,6};
	unordered_set<long long int> seen;
	int32_t node = 2;
	visit(node, counts, seen);
	CHECK(counts[2] == 4);
	CHECK(seen.find(2) != seen.end());
}

TEST_CASE("Test syncmerstats::visit: mark syncmer as non-unique.") {
	vector<int32_t> counts(5,0);
	unordered_set<long long int> seen;
	int32_t first = 4;
	int32_t second = -4;
	visit(first, counts, seen);
	CHECK(counts[4] == 1);
	CHECK(seen.find(4) != seen.end());
	visit(second, counts, seen);
	CHECK(counts[4] == -1);
	CHECK(seen.find(-4) == seen.end());
}

TEST_CASE("Test syncmerstats::get_max: read sample file.") {
	string filename = string(TEST_DATA_DIR) + "small.1khash";
	CHECK(get_max(filename) == 11);
}

TEST_CASE("Test syncmerstats::get_max missing file.") {
	string non_existent = "non-existent.1khash";
	CHECK_THROWS_AS(get_max(non_existent), runtime_error);
}


// =============================================================================
// The following test cases were generated by Claude (see: tests/data/README.md)
// =============================================================================

#include "test_helpers.hpp"

// small.1path / small.1gbwt: 2 Quelldateien, 4 Pfade, 11 Syncmere.
// Syncmere 3-11 liegen auf genau einem Pfad, 1 und 2 auf keinem.
static const string SMALL_SYNCMERS =
	"syncmer_ID\ttotal_count\n"
	"1\t0\n" "2\t0\n" "3\t1\n" "4\t1\n" "5\t1\n" "6\t1\n"
	"7\t1\n" "8\t1\n" "9\t1\n" "10\t1\n" "11\t1\n";
static const string SMALL_HISTOGRAM = "0\t2\n" "1\t9\n" "2\t0\n";

// small_repeats.1path: wie small.1path, aber Pfad 3 (Quelldatei 2) ist "3 -8 -8" statt "-7 -8 -9":
//  - Syncmer 3 kommt in beiden Quelldateien vor -> Count 2
//  - Syncmer 8 kommt in Quelldatei 2 doppelt vor -> nicht eindeutig, fehlt in der Ausgabe
//  - Syncmere 7 und 9 werden nicht mehr besucht -> Count 0
static const string REPEATS_SYNCMERS =
	"syncmer_ID\ttotal_count\n"
	"1\t0\n" "2\t0\n" "3\t2\n" "4\t1\n" "5\t1\n" "6\t1\n"
	"7\t0\n" "9\t0\n" "10\t1\n" "11\t1\n";
static const string REPEATS_HISTOGRAM = "0\t4\n" "1\t5\n" "2\t1\n";

// small_subset.tsv enthält die Syncmere 3, 5, 7, 8, 9, 10, 11.
// Spalten: Pfadnummer, Abstand zum vorherigen Syncmer aus der Teilmenge, Syncmer-ID
//  Pfad 1: 3 (Pos. 2), 5 (Pos. 6)            -> 5 hat Abstand 4
//  Pfad 2: nur Syncmer 6                     -> keine Ausgabe
//  Pfad 3: 7 (Pos. 2), 8 (Pos. 4), 9 (Pos. 6) -> 8 und 9 haben Abstand 2
//  Pfad 4: 10 (Pos. 2), 11 (Pos. 3)          -> 11 hat Abstand 1
static const string SMALL_DISTANCES =
	"1\t4\t5\n"
	"3\t2\t8\n"
	"3\t2\t9\n"
	"4\t1\t11\n";

TEST_CASE("Test syncmerstats::get_max: khash file without t lines.") {
	string filename = data_path("small_no_t_lines.1khash");
	CHECK_THROWS_WITH_AS(get_max(filename), "Error: khash file does not contain any t lines.", runtime_error);
}

TEST_CASE("Test syncmerstats::compute_syncmer_stats_from_paths") {
	string path = data_path("small.1path");
	string khash = data_path("small.1khash");

	SUBCASE("sample files") {
		string out = output_path("stats_paths");
		REQUIRE(compute_syncmer_stats_from_paths(path, khash, out) == 0);
		CHECK(read_file(out + "_syncmers.tsv") == SMALL_SYNCMERS);
		CHECK(read_file(out + "_histogram.tsv") == SMALL_HISTOGRAM);
	}

	SUBCASE("shared and non-unique syncmers") {
		string repeats = data_path("small_repeats.1path");
		string out = output_path("stats_paths_repeats");
		REQUIRE(compute_syncmer_stats_from_paths(repeats, khash, out) == 0);
		CHECK(read_file(out + "_syncmers.tsv") == REPEATS_SYNCMERS);
		CHECK(read_file(out + "_histogram.tsv") == REPEATS_HISTOGRAM);
	}

	SUBCASE("missing path file") {
		string missing = data_path("non-existent.1path");
		string out = output_path("stats_paths_missing_path");
		CHECK(compute_syncmer_stats_from_paths(missing, khash, out) == 1);
	}

	SUBCASE("missing khash file") {
		string missing = data_path("non-existent.1khash");
		string out = output_path("stats_paths_missing_khash");
		CHECK(compute_syncmer_stats_from_paths(path, missing, out) == 1);
	}

	SUBCASE("paths not ordered by source file") {
		string unordered = data_path("small_unordered.1path");
		string out = output_path("stats_paths_unordered");
		CHECK(compute_syncmer_stats_from_paths(unordered, khash, out) == 1);
	}

	SUBCASE("output file cannot be created") {
		string out = output_path("non-existent-dir/stats");
		CHECK(compute_syncmer_stats_from_paths(path, khash, out) == 1);
	}
}

TEST_CASE("Test syncmerstats::compute_syncmer_stats_from_gbwt") {
	string gbwt = data_path("small.1gbwt");
	string khash = data_path("small.1khash");

	SUBCASE("sample files give the same result as the path version") {
		string out = output_path("stats_gbwt");
		REQUIRE(compute_syncmer_stats_from_gbwt(gbwt, khash, out) == 0);
		CHECK(read_file(out + "_syncmers.tsv") == SMALL_SYNCMERS);
		CHECK(read_file(out + "_histogram.tsv") == SMALL_HISTOGRAM);
	}

	SUBCASE("missing gbwt file") {
		string missing = data_path("non-existent.1gbwt");
		string out = output_path("stats_gbwt_missing");
		CHECK(compute_syncmer_stats_from_gbwt(missing, khash, out) == 1);
	}

	SUBCASE("missing khash file") {
		string missing = data_path("non-existent.1khash");
		string out = output_path("stats_gbwt_missing_khash");
		CHECK(compute_syncmer_stats_from_gbwt(gbwt, missing, out) == 1);
	}

	SUBCASE("output file cannot be created") {
		string out = output_path("non-existent-dir/stats");
		CHECK(compute_syncmer_stats_from_gbwt(gbwt, khash, out) == 1);
	}
}

TEST_CASE("Test syncmerstats::compute_syncmer_distances_from_paths") {
	string path = data_path("small.1path");
	string khash = data_path("small.1khash");
	string subset = data_path("small_subset.tsv");

	SUBCASE("sample files") {
		string out = output_path("distances.tsv");
		REQUIRE(compute_syncmer_distances_from_paths(path, khash, subset, out) == 0);
		CHECK(read_file(out) == SMALL_DISTANCES);
	}

	SUBCASE("missing path file") {
		string missing = data_path("non-existent.1path");
		string out = output_path("distances_missing_path.tsv");
		CHECK(compute_syncmer_distances_from_paths(missing, khash, subset, out) == 1);
	}

	SUBCASE("missing khash file") {
		string missing = data_path("non-existent.1khash");
		string out = output_path("distances_missing_khash.tsv");
		CHECK(compute_syncmer_distances_from_paths(path, missing, subset, out) == 1);
	}

	SUBCASE("missing syncmer set file") {
		string missing = data_path("non-existent.tsv");
		string out = output_path("distances_missing_set.tsv");
		CHECK(compute_syncmer_distances_from_paths(path, khash, missing, out) == 1);
	}

	SUBCASE("syncmer ID larger than number of syncmers") {
		string invalid = data_path("small_subset_invalid.tsv");
		string out = output_path("distances_invalid_set.tsv");
		CHECK(compute_syncmer_distances_from_paths(path, khash, invalid, out) == 1);
	}

	SUBCASE("o line without preceding z line") {
		string broken = data_path("small_o_without_z.1path");
		string out = output_path("distances_o_without_z.tsv");
		CHECK(compute_syncmer_distances_from_paths(broken, khash, subset, out) == 1);
	}

	SUBCASE("output file cannot be created") {
		string out = output_path("non-existent-dir/distances.tsv");
		CHECK(compute_syncmer_distances_from_paths(path, khash, subset, out) == 1);
	}
}
