#ifndef TEST_HELPERS_HPP
#define TEST_HELPERS_HPP

#include <fstream>
#include <sstream>
#include <string>
#include <vector>

/** This file was generated by Claude. **/

inline std::string data_path(const std::string& name) {
	return std::string(TEST_DATA_DIR) + name;
}

inline std::string output_path(const std::string& name) {
	return std::string(TEST_OUTPUT_DIR) + name;
}

// reads file content as a string, "" if non-existent
inline std::string read_file(const std::string& path) {
	std::ifstream in(path);
	std::stringstream ss;
	ss << in.rdbuf();
	return ss.str();
}

inline bool file_exists(const std::string& path) {
	return std::ifstream(path).good();
}

// builts an argv array
struct Args {
	std::vector<std::string> storage;
	std::vector<char*> argv;
	explicit Args(std::vector<std::string> args) : storage(std::move(args)) {
		for (auto& s : storage) argv.push_back(s.data());
		argv.push_back(nullptr);
	}
	int argc() const { return static_cast<int>(storage.size()); }
	char** data() { return argv.data(); }
};

#endif // TEST_HELPERS_HPP
